name: cg_openmm
channels:
  - schrodinger/label/archive
  - openeye
  - intel
  - anaconda
  - conda-forge
  - schrodinger
  - ambermd
  - omnia
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py36_0
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py36_0
  - ambermini=16.16.0=7
  - ambertools=19.0=0
  - anaconda-client=1.7.2=py36_0
  - anaconda-navigator=1.9.6=py36_0
  - anaconda-project=0.8.2=py36_0
  - apbs=1.5=h14c3975_3
  - asn1crypto=0.24.0=py36_0
  - astroid=2.2.5=py36_0
  - astropy=3.0.5=py36h7b6447c_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - babel=2.7.0=py_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py36_1
  - backports.os=0.1.1=py36_0
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.7.1=py36_1
  - bitarray=0.8.3=py36h14c3975_0
  - bkcharts=0.2=py36_0
  - blas=1.1=openblas
  - blaze=0.11.3=py36_0
  - bleach=3.1.0=py36_0
  - blosc=1.16.3=hd408876_0
  - bokeh=1.0.4=py36_0
  - boto=2.49.0=py36_0
  - bottleneck=1.2.1=py36h035aef0_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - cerberus=1.1=py_1
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - cftime=1.0.3.4=py36hdd07704_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py36_0
  - cloudpickle=0.8.0=py36_0
  - clusterutils=0.3.1=py36_1
  - clyent=1.2.2=py36_1
  - colorama=0.4.1=py36_0
  - conda=4.7.11=py36_0
  - conda-build=3.17.8=py36_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.3.11=py36_0
  - conda-verify=3.1.1=py36_0
  - contextlib2=0.5.5=py36_0
  - cryptography=2.7=py36h1ba5d50_0
  - curl=7.63.0=hbc83047_1000
  - cycler=0.10.0=py36_0
  - cython=0.29.6=py36he6710b0_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=1.1.4=py36_1
  - dask-core=1.1.4=py36_1
  - datashape=0.5.4=py36_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - distributed=1.26.0=py36_1
  - docopt=0.6.2=py36_1
  - docutils=0.14=py36_0
  - entrypoints=0.3=py36_0
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.0.2=py36h14c3975_2
  - fastcluster=1.1.20=np112py36_0
  - fftw3f=3.3.4=2
  - filelock=3.0.10=py36_0
  - flask=1.0.2=py36_1
  - flask-cors=3.0.7=py36_0
  - fontconfig=2.13.0=h9420a91_0
  - freemol=1.158=py36_1
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - future=0.17.1=py36_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.4.0=py36h7b6447c_0
  - glew=2.0.0=0
  - glib=2.56.2=hd408876_0
  - glob2=0.6=py36_1
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - graphite2=1.3.12=h23475e2_2
  - greenlet=0.4.15=py36h7b6447c_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=nompi_py36hf008753_1102
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - imageio=2.5.0=py36_0
  - imagesize=1.1.0=py36_0
  - importlib_metadata=0.8=py36_0
  - intel-openmp=2019.1=144
  - intelpython=2019.4=0
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.3.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - isort=4.3.15=py36_0
  - itsdangerous=1.1.0=py36_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4=py36_0
  - jedi=0.13.3=py36_0
  - jeepney=0.4=py36_0
  - jinja2=2.10.1=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.4=py36hf63ae98_0
  - jupyterlab_server=0.2.0=py36_0
  - keyring=18.0.0=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - krb5=1.16.1=h173b8e3_7
  - latexcodec=1.0.1=py36_0
  - lazy-object-proxy=1.3.1=py36h14c3975_2
  - libarchive=3.3.3=h5d8350f_5
  - libcurl=7.63.0=h20c2e04_1000
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - liblief=0.9.0=h7725739_1
  - libnetcdf=4.6.1=h11d0813_2
  - libopenblas=0.3.3=h5a2b251_3
  - libpng=1.6.35=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.0=h1ba5d50_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libtool=2.4.6=h7b6447c_5
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - llvmlite=0.28.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lxml=4.3.0=py36hefd8a0e_0
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.0.2=py36h5429711_0
  - mccabe=0.6.1=py36_1
  - mdtraj=1.9.1=py36_0
  - mengine=1=h14c3975_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2017.0.4=h4c4d0af_0
  - mock=3.0.5=py36_0
  - more-itertools=6.0.0=py36_0
  - mpc=1.1.0=h10f8cd9_1
  - mpeg_encode=1=h14c3975_1
  - mpfr=4.0.1=hdf1c602_3
  - mpi4py=2.0.0=py36_2
  - mpich=3.2=4
  - mpmath=1.1.0=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - msmbuilder=3.8.0=np112py36_0
  - mtz2ccp4_px=1.0=h9ac9557_3
  - multipledispatch=0.6.0=py36_0
  - navigator-updater=0.2.1=py36_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py36h808af73_0
  - networkx=2.2=py36_1
  - nltk=3.4=py36_1
  - nose=1.3.7=py36_2
  - notebook=5.7.6=py36_0
  - numba=0.43.0=py36h962f231_0
  - numexpr=2.6.9=py36h637b7d7_1000
  - numpy=1.12.1=py36_0
  - numpydoc=0.9.1=py_0
  - odo=0.5.1=py36_0
  - olefile=0.46=py36_0
  - openblas=0.2.19=2
  - openeye-toolkits=2019.4.2=py36_0
  - openmm=7.3.1=py36_cuda92_rc_2
  - openmmtools=0.16.0=py36_0
  - openmoltools=0.8.3=py36_0
  - openpyxl=2.6.1=py36_1
  - openssl=1.1.1=h7b6447c_0
  - oset=0.1.3=py36_1
  - packaging=19.0=py36_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36_1
  - panedr=0.5.2=py_0
  - pango=1.42.4=h049681c_0
  - parso=0.3.4=py36_0
  - partd=0.3.10=py36_1
  - patchelf=0.9=he6710b0_3
  - path.py=11.5.0=py36_0
  - pathlib2=2.3.3=py36_0
  - patsy=0.5.1=py36_0
  - pbr=5.3.0=py_0
  - pcre=8.42=h439df22_0
  - pdb2pqr=2.1.1=py36_1
  - pdbfixer=1.5=py36_0
  - pep8=1.7.1=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - pkginfo=1.5.0.1=py36_0
  - pluggy=0.9.0=py36_0
  - ply=3.11=py36_0
  - pmw=2.0.1=py36_2
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.1=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - py-lief=0.9.0=py36h7725739_1
  - pybtex=0.18=py36_0
  - pybtex-docutils=0.2.1=py36_1
  - pycodestyle=2.5.0=py36_0
  - pycosat=0.6.3=py36h14c3975_0
  - pycparser=2.19=py36_0
  - pycrypto=2.6.1=py36h14c3975_9
  - pycurl=7.43.0.2=py36h1ba5d50_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.4.2=py_0
  - pyhmc=0.1.2=np112py36_1
  - pylint=2.3.1=py36_0
  - pymbar=3.0.1.beta0=np112py36_0
  - pymol=2.0.6=py36_0
  - pyodbc=4.0.26=py36he6710b0_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - pysocks=1.7.0=py36_0
  - pytables=3.5.2=py36h71ec239_1
  - pytest=4.3.1=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.5.0=py36_0
  - pytest-doctestplus=0.3.0=py36_0
  - pytest-openfiles=0.3.2=py36_0
  - pytest-remotedata=0.3.1=py36_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - python-libarchive-c=2.8=py36_6
  - pytz=2019.1=py_0
  - pywavelets=1.0.2=py36hdd07704_0
  - pyyaml=5.1.1=py36h7b6447c_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.5.7=py36_1
  - qtconsole=4.4.3=py36_0
  - qtpy=1.7.0=py36_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - rigimol=1.3=2
  - rope=0.12.0=py36_0
  - ruamel_yaml=0.15.46=py36h14c3975_0
  - scikit-image=0.14.2=py36he6710b0_0
  - scikit-learn=0.18.1=np112py36_blas_openblas_200
  - scipy=0.18.1
  - seaborn=0.9.0=py36_0
  - secretstorage=3.1.1=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=1.9.0=py_0
  - sortedcollections=1.1.2=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=1.8=py36_0
  - sphinx=2.1.2=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-bibtex=0.3.2=py36_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.0=py36_1
  - spyder=3.3.3=py36_0
  - spyder-kernels=0.4.2=py36_0
  - sqlalchemy=1.3.1=py36h7b6447c_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - sympy=1.3=py36_0
  - tbb=2019.4=hfd86e86_0
  - tblib=1.3.2=py36_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=6.0.1=py36h7b6447c_0
  - tqdm=4.31.1=py36_1
  - traitlets=4.3.2=py36_0
  - typed-ast=1.3.1=py36h7b6447c_0
  - unicodecsv=0.14.1=py36_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.24.2=py36_0
  - vmd=1.9.3=hf484d3e_1
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - wrapt=1.11.1=py36h7b6447c_0
  - wurlitzer=1.0.2=py36_0
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.1.5=py36_0
  - xlwt=1.3.0=py36_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.9=h516909a_1002
  - xorg-libxinerama=1.1.4=hf484d3e_1000
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - yank=0.21.2=py36_0
  - zeromq=4.2.5=hf484d3e_1
  - zict=0.1.4=py36_0
  - zipp=0.3.3=py36_1
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - deap==1.3.0
    - packmol-memgen==1.0.5rc0
    - parmed==3.2.0
    - pdb4amber==1.7.dev0
    - pymsmt==19.0
    - pytraj==2.0.5
    - sander==16.0
    - sklearn-genetic==0.2
